### PR TITLE
Pre-commit hook to clear cell outputs.

### PR DESCRIPTION
**Pull request by fayvor**
- Add pre-commit config with nbstripout. This will reset cell output and execution_counts.

To activate pre-commit hooks, run `pre-commit install` in the repository root dir.

### CODE REVIEW

**Comment by rawkintrevo** [comment]
What's up with CodeQL?
https://github.com/kynan/nbstripout has a goofy license, and I don't understand our ROE with other licenses, is it legit?
Can this also go to the cookbook repo?

**Comment by fayvor** [comment]
> What's up with CodeQL?

Not sure about CodeQL. Here is the error:
```CodeQL did not detect any code written in languages supported by this CodeQL distribution (HTML, Python, JavaScript/TypeScript, C#, XML, CSV, Swift, YAML, Ruby, Java/Kotlin, C/C++, Go or Java Properties Files). Confirm that there is some source code for one of these languages in the project.```

**Comment by rawkintrevo** [comment]
Yea, idk what that check is or why it exists, but I saw the failing reason.

The license and open a ticket in the other repo were my main comments.

**Comment by fayvor** [comment]
> https://github.com/kynan/nbstripout has a goofy license, and I don't understand our ROE with other licenses, is it legit?

It looks ok to me. We don't check in any of this code; it's just used as a tool when committing.

> Can this also go to the cookbook repo?

Yes, I'll add this to the other repos.

**Comment by fayvor** [comment]
Looks like [CodeQL](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security) is a vulnerability scanner.

**Pull request merged**
